### PR TITLE
bevy-0.15

### PR DESCRIPTION
**Pull request by Multirious**
Todo:
- [x] Migrate `bevy_time_runner` to 0.15 https://github.com/Multirious/bevy_time_runner/issues/5
- [x] Migrate `bevy_tween` to 0.15 and upgrade other related dependencies
- [x] Merge #44
- [x] Do something about EaseFunction
- [ ] Experiment with `all_tuples!()` macro (later im too lazy)
- [x] Update nightly docrs stuff.
- [x] Update examples
- [x] Update changelog
- [x] Bump version to 0.7

### CODE REVIEW

**Comment by patrickariel** [comment]
One annoying thing about the migration is that there's now an `EaseFunction` upstream (and it's not a component). So if you have imports like this:

```rust
use bevy::prelude::*;
use bevy_tween::prelude::*;
```

Trying to use `EaseFunction` will trigger an ambiguity error. Maybe it could be renamed?

**Comment by Multirious** [comment]
We probably need to alias it to something like `TweenEaseFunction` and remove the original from prelude so user can easily global replace the names. We should also implement `From<bevy::curve::EaseFunction>` and support the new variants. For bevy_tween 0.18, the APIs probably going to be drastically changed to use the new Bevy's animation stuff and deprecate the old EaseFunction. It should also be simple to global replace the aliased `TweenEaseFunction` too.

**Comment by patrickariel** [comment]
I'm leaning on renaming it. `EaseFunction` is used everywhere, so having to use explicit imports kinda defeats the purpose of preludes. How about `EaseKind`? It's shorter compared to adding another suffix.

**Comment by Multirious** [comment]
Yeah, decided to use EaseKind. It's a temporary name anyways.

**Comment by Multirious** [comment]
This PR may take a bit more time than expected. The examples ain't working like it should and I have no idea why.

**Pull request merged**
